/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 615b85cfe4e0c332adb1a61d1c4669c3)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "CodeGeneratorAgent" | "UserAppSandboxService" | "DORateLimitStore" | "UserSecretsStore";
	}
	interface Env {
		VibecoderStore: KVNamespace;
		TEMPLATES_REPOSITORY: "https://github.com/cloudflare/vibesdk-templates";
		ALLOWED_EMAIL: "codyboring@me.com";
		DISPATCH_NAMESPACE: "boringbuilder-apps";
		ENABLE_READ_REPLICAS: string;
		CLOUDFLARE_AI_GATEWAY: "boringbuilder_gateway";
		PLATFORM_MODEL_PROVIDERS: "google-ai-studio,anthropic,deepseek,openrouter,grok,openai";
		PLATFORM_CAPABILITIES: {"features":{"app":{"enabled":true},"presentation":{"enabled":true},"general":{"enabled":false}},"version":"1.0.0"};
		CUSTOM_DOMAIN: "build.getboring.io";
		CUSTOM_PREVIEW_DOMAIN: "getboring.io";
		MAX_SANDBOX_INSTANCES: "10";
		SANDBOX_INSTANCE_TYPE: "standard-4";
		WORKERS_DEV_HOSTNAME: "boringbuilder.codyboring.workers.dev";
		ANTHROPIC_API_KEY: string;
		OPENAI_API_KEY: string;
		GOOGLE_AI_STUDIO_API_KEY: string;
		OPENROUTER_API_KEY: string;
		CEREBRAS_API_KEY: string;
		DEEPSEEK_API_KEY: string;
		GROQ_API_KEY: string;
		GOOGLE_VERTEX_AI_API_KEY: string;
		SANDBOX_SERVICE_API_KEY: string;
		SANDBOX_SERVICE_TYPE: string;
		SANDBOX_SERVICE_URL: string;
		CLOUDFLARE_API_TOKEN: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_AI_GATEWAY_URL: string;
		CLOUDFLARE_AI_GATEWAY_TOKEN: string;
		SERPAPI_KEY: string;
		GOOGLE_CLIENT_SECRET: string;
		GOOGLE_CLIENT_ID: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		JWT_SECRET: string;
		AI_PROXY_JWT_SECRET: string;
		ENTROPY_KEY: string;
		ENVIRONMENT: string;
		SECRETS_ENCRYPTION_KEY: string;
		ALLOCATION_STRATEGY: string;
		GITHUB_EXPORTER_CLIENT_ID: string;
		GITHUB_EXPORTER_CLIENT_SECRET: string;
		CF_ACCESS_ID: string;
		CF_ACCESS_SECRET: string;
		SENTRY_DSN: string;
		USE_TUNNEL_FOR_PREVIEW: string;
		USE_CLOUDFLARE_IMAGES: string;
		CodeGenObject: DurableObjectNamespace<import("./worker/index").CodeGeneratorAgent>;
		Sandbox: DurableObjectNamespace<import("./worker/index").UserAppSandboxService>;
		DORateLimitStore: DurableObjectNamespace<import("./worker/index").DORateLimitStore>;
		UserSecretsStore: DurableObjectNamespace<import("./worker/index").UserSecretsStore>;
		TEMPLATES_BUCKET: R2Bucket;
		DB: D1Database;
		DISPATCHER: DispatchNamespace;
		API_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
		AI: Ai;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEMPLATES_REPOSITORY" | "ALLOWED_EMAIL" | "DISPATCH_NAMESPACE" | "ENABLE_READ_REPLICAS" | "CLOUDFLARE_AI_GATEWAY" | "PLATFORM_MODEL_PROVIDERS" | "PLATFORM_CAPABILITIES" | "CUSTOM_DOMAIN" | "CUSTOM_PREVIEW_DOMAIN" | "MAX_SANDBOX_INSTANCES" | "SANDBOX_INSTANCE_TYPE" | "WORKERS_DEV_HOSTNAME">> {}
}
